# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://127.0.0.1:8080/test/mock
Content-Type: application/x-www-form-urlencoded

type=AUTH_REQUEST&message={"accessToken":"A"}

###
POST http://127.0.0.1:8080/test/mock
Content-Type: application/x-www-form-urlencoded

type=CHAT_SEND_TO_ONE_REQUEST&message={"toUser":"B", "msgId":1, "content":"who are u"}

###
POST http://127.0.0.1:8081/test/mock
Content-Type: application/x-www-form-urlencoded

type=AUTH_REQUEST&message={"accessToken":"B"}

###